### ISSUE TITLE
safeHtml is deprecated

### ISSUE THREAD

**Issue by vaughn-taylor** [spicywebau/craft-embedded-assets#100]
#### Description

I'm seeing the following deprecation error in Deprecation Warnings

"The embedded asset property `safeHtml` is now deprecated. Use a combination of the `isSafe()` method and the `code` property instead."

I'm not clear on how to fix this? This is functional:

`{{ embed ? embed.safeHtml|raw }}`

I've tried this, but it's obviously not correct:

`{{ embeddedAsset ? isSafe(embed) }}`

How do I correct this?

#### Other information
- Embedded Assets version: 2.0.2
- Craft CMS version: 3.1.20.1

**Comment by ttempleton** [comment]
Hi @vaughn-taylor,

This could be achieved using:
`{{ embed and embed.isSafe() ? embed.code }}`

Alternatively,
`{{ embed ? embed.html }}`
This will perform the `isSafe()` check and return the `code` if successful; otherwise, it will provide an `<img>` or `<a>` element for the embedded asset, depending on the embedded asset type.

Hope that helps!  And for more information on converting to the Craft 3 equivalents to old methods/properties from Embedded Assets for Craft 2, see [Templating#Upgrading from Craft 2](https://github.com/spicywebau/craft-embedded-assets/blob/master/docs/templating.md#upgrading-from-craft-2).  That section notes `html` as being the preferred replacement for `safeHtml`, but use whichever replacement would best suit your project.
