### ISSUE TITLE
Possible to update existing embedded asset?

### ISSUE THREAD

**Issue by oyvindostmo** [spicywebau/craft-embedded-assets#106]
#### Description
Hi,
we have a multisite with the same YouTube embedded assets being used across a bunch of entries for about 15 "partner sites" with similar content. Now we need to replace a few of these videos, and using the default "Replace file" function in Assets just opens an upload dialogue.
Is it possible to change the embed URL of an existing embedded asset? If not, this is very much wanted as a new feature :)

#### Other information
- Embedded Assets version: 2.0.2
- Craft CMS version: 3.2.0

**Comment by pvldigital** [comment]
Hi @oyvindostmo,

Embedded assets currently doesn't have a feature to directly replace the JSON file with another which is why it displays the default Craft CMS upload dialog. We'll add this on the roadmap for a future release.

What you can do in the meantime is create a channel section that contains the asset and link to it in existing entries.

**Comment by oyvindostmo** [comment]
Ok thanks, that was my initial plan B, so I'll go with that for now until the feature is implemented :)

**Comment by ttempleton** [comment]
This issue was resolved by the addition of the replace button on the asset index page in Embedded Assets 2.2.0.
