### ISSUE TITLE
Instagram URL signature expired

### ISSUE THREAD

**Issue by djrees** [spicywebau/craft-embedded-assets#114]
When embedding an instagram post (photo or video), the plugin works great and I can see the images pulling through. However, after a while the images stop appearing on my site and I get 403 error message. When loading the URL of the image directly, I get `URL signature expired` message.

If I embed the post again, the images pull through fine.

Any suggestions?

**Comment by craigliggins** [comment]
Any movement on providing a solution for this?

**Comment by pvldigital** [comment]
Hi @djrees and @craigliggins,

Seems to be related to the changes Instagram has made. Re-adding the post will generate a new signature but it's not a good long term solution (since the signature will expire and you'll have to add it again).

If it's only 1 image, you could try using the url with the size parameter `e.g https://www.instagram.com/p/B3kwCXrA8xt/media/?size=l` when templating. It should generate the image with the correct signature.

I'll look into implementing a function that'll allow embedded assets regenerate the file instead of re-adding it.

PS: if possible, can you attach the problem json file.

**Comment by 23d1** [comment]
@pvldigital  that seems to be the solution that works across the board. Any chance of this being implemented soon. Regenerating existing embeds would be amazing as well.

**Comment by pvldigital** [comment]
@23d1 thanks for the file!

I'm currently implementing a replace button specifically for embedded assets which should make it easier to reupload the file.

After that's done i'll have a more in depth look on how to automatically regenerate the file if it's expired.

**Comment by langlers** [comment]
Facing this issue as well. Looking forward to your solution. If I can help test or provide additional data, let me know.

**Comment by pvldigital** [comment]
I've made some changes for Instagram on this branch https://github.com/spicywebau/craft-embedded-assets/tree/feature/instagram-auto-refresh for the issue.

If the date difference is more than 13 days and if the image doesn't return 200 then it'll automatically replace the file with a new one that has an updated signature.

It's not ready for release as I'm currently testing but I'll keep you all updated.

**Comment by jasonwoodland** [comment]
We released a fix for this issue. Feel free to reopen this if you have any more problems.

**Comment by pushp1997** [comment]
`/media?size=l` works great for posts, what's the alternative for Instagram reels?

**Comment by prafulbagai** [comment]
@pushp1997 were you able to find the similar approach for reels?

**Comment by pushp1997** [comment]
> @pushp1997 were you able to find the similar approach for reels?

Nope, couldn't find any solution!
