### ISSUE TITLE
Expose embedded asset creation method(s)

### ISSUE THREAD

**Issue by joshuabaker** [spicywebau/craft-embedded-assets#130]
@pvldigital, please can we have a way to create embedded asset instances from an array. 

Use case here is if we already have the JSON decoded and want to avoid the additional call.

It looks like this is a matter of exposing the `createEmbeddedAsset`, however, there’s something going on with Instagram in the `getEmbeddedAsset` method that I don’t fully understand right now (hence issue and not a PR).

**Comment by pvldigital** [comment]
Hi @joshuabaker,

Sure we can have a look into that functionality.
Re Instagram: it's because the signatures of the images expires after a certain amount of time. The code within `getEmbeddedAsset` basically refreshes the instagram json if it is expired.

**Comment by joshuabaker** [comment]
We’re after something like this…

```twig
{% set contents = asset.contents %}
{% set decoded = contents|json_decode %}

{% if craft.embeddedAssets.isEmbed(decoded) %}
  {% set embeddedAsset = craft.embeddedAssets.parseJson(decoded) %}
  …
{% else %}
  …
{% endif %}
```

I’m wondering about the best approach for this.

Is there any way that we can get the Instagram logic out of the `getEmbeddedAsset` method call?

**Comment by joshuabaker** [comment]
I guess the `fromArray` method, or whatever it’s named, could require an `Asset` instance as a second parameter.

The only other way I can think to do this is via the database, with the asset only used as a reference. Quite a departure from how things are currently working though.

**Comment by ttempleton** [comment]
I've added `craft.embeddedAssets.create()` to Embedded Assets 2.10.0, which takes the array as an argument. It isn't going to do the same checks that `get()` does to make sure the data it's getting for an Instagram embed is still valid, but one other new feature in 2.10.0 as well as other previously existing functionality will hopefully help anyone who needs to get the asset contents for an Instagram embed for any reason:

- The new console command for refreshing embedded assets depending on the provider: `php craft embeddedassets/refresh/by-provider --provider=Instagram`
- `craft.embeddedAssets.get()` could be used to get the embedded asset, invoking the automatic Instagram refreshing in `Service::getEmbeddedAsset()` if seven days have passed since it was last refreshed, followed by the use of `EmbeddedAsset::jsonSerialize()` to get the array
