### ISSUE TITLE
Unable to delete file with instagram embed

### ISSUE THREAD

**Issue by skoften** [spicywebau/craft-embedded-assets#135]
Updated to 2.2.6, getting the following error when trying to embed some instagram posts;

```
2020-06-03 13:03:10 [-][1][-][warning][craft\services\AssetTransforms::deleteAllTransformData] Unable to delete the file "/var/www/xxx/storage/runtime/assets/sources/804289.json".
2020-06-03 13:03:08 [-][1][-][info][application] $_GET = [
    'p' => 'cp/actions/embeddedassets/actions/save'
]

$_POST = [
    'url' => 'https://www.instagram.com/p/CAx8r9yBscw/'
    'folderId' => '9c87a0cb-0fb6-4afc-bd00-84302ebbe47a'
```
It doesn't happen with all url's...

**Comment by ttempleton** [comment]
This warning in the log is happening due to Craft trying to delete data associated with asset transforms when saving or deleting an asset, but asset transform data doesn't exist in the case of an embedded asset.  Unfortunately there's currently nothing we can do about this, but I'm going to leave the issue open in case that changes in the future.

**Comment by ttempleton** [comment]
Actually, it looks like Craft gives this warning when you're deleting a JSON file in general.  It's still a harmless warning in that case since the file it's trying to delete never existed, but any improvements to this warning, e.g. when it occurs or what it says, would need to be done on Craft's end.
