### ISSUE TITLE
Could not retreive embed information 

### ISSUE THREAD

**Issue by skoften** [spicywebau/craft-embedded-assets#145]
Getting a "Could not retreive embed information"-error when trying to embed Youtube videos.

![Screenshot 2020-10-13 at 19 50 11](https://user-images.githubusercontent.com/1286410/95897858-7dadee80-0d8e-11eb-8bf0-ffe93aea9d1a.jpg)

![Screenshot 2020-10-13 at 19 50 13](https://user-images.githubusercontent.com/1286410/95897866-80104880-0d8e-11eb-839b-53f0eae571c2.jpg)

Happens on all youtube links.

Running version 2.4.0 on Craft CMS 3.5.12.1

**Comment by jamiewade** [comment]
_Maybe_ related? https://github.com/spicywebau/craft-embedded-assets/issues/147

**Comment by ttempleton** [comment]
YouTube embeds seem to be working in my testing of both the Embedded Assets plugin and the [Embed library demo](https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fyoutu.be%2FawRTEupL1qA), so I think this is more likely an issue with your server connecting to YouTube.

Are you able to embed a non-shortened YouTube URL?

Are you able to run `curl -L -o <filename to save> https://youtu.be/awRTEupL1qA` from the server with success?

**Comment by skoften** [comment]
That works fine:

![Screenshot 2020-10-21 at 09 52 21](https://user-images.githubusercontent.com/1286410/96690647-3cb46c00-1384-11eb-93af-12d91db954c5.jpg)

**Comment by ttempleton** [comment]
In that case, this probably is an issue with the Embed library.  It's important to note that the actual connection to the provider is performed by Embed, so if there's some issue with Embed that prevents connection to a provider, there's nothing we can really do about it, unfortunately.

I'd recommend setting up a [test of Embed 3](https://github.com/oscarotero/Embed/tree/v3.x#usage) on the same server, accessing the same URL.  If that doesn't work, I'd recommend opening an issue over there, but I'll be happy to reopen this issue if it turns out that works while using Embedded Assets still doesn't work.

I'd also recommend trying a non-shortened URL as suggested in my previous comment, as that seems like it would be a suitable workaround for the issue if it works.

**Comment by dennisfrank** [comment]
@skoften Have you found a solution? We are having exactly the same problem.

**Comment by skoften** [comment]
@dennisfrank if I remember correctly, we added the oEmbed product to the Facebook app:

![Screenshot 2021-03-23 at 18 19 08](https://user-images.githubusercontent.com/1286410/112189548-6825d600-8c04-11eb-9061-fa44cfb2d08f.jpg)

**Comment by dennisfrank** [comment]
Thanks @skoften. I'm not sure I am following you here. :)

Facebook App? Didn't you have the issue with YouTube?

**Comment by skoften** [comment]
My bad, confused this issue with the Instagram issue! :-(
