### ISSUE TITLE
Instagram requires access token for oEmbed now

### ISSUE THREAD

**Issue by sjcallender** [spicywebau/craft-embedded-assets#150]
#### Description
Starting Oct 24, 2020, Facebook/Instagram requires an access token (combo of app id and client token) to use their oEmbed product, which is what this plugin uses. See their notice: https://developers.facebook.com/docs/instagram/oembed/
![image](https://user-images.githubusercontent.com/984311/97515947-7b3fbd00-1968-11eb-95f0-7f3c0e6634d8.png)

I noticed this because a client site is getting all HTTP 400 errors

The dependency package [embed/embed](https://github.com/oscarotero/Embed) is getting updated to use the new API. The new code is sitting the [v3.x branch](https://github.com/oscarotero/Embed/pull/398) right now.

Looks like this will pair with some new settings options: https://github.com/oscarotero/Embed#settings

**More than anything I wanted to put this on your radar with the hopes you can plan to address it sooner than later once the changes in embed/embed are released in a new version.**

Edited:
More PR work submitted for the embed/embed package: https://github.com/oscarotero/Embed/pull/399

**Comment by ttempleton** [comment]
Looking at the merged pull request for Embed 3, it's just using the Facebook API key as the access token, which Embedded Assets already has a setting for.  If that's it and there are no extra settings we need to pass, then we just need to enforce an Embed update.

I've just released Embedded Assets 2.4.3 which updates the Embed minimum requirement; does that resolve the issue?

**Comment by skoften** [comment]
No luck yet, we can't add any instagram embeds anymore at this moment.

**Comment by skoften** [comment]
Edit: tried to update to the latest embed/embed library (https://github.com/oscarotero/Embed/releases/tag/v4.3.0) , but that seems impossible for now;

![Screenshot 2020-11-06 at 13 17 58](https://user-images.githubusercontent.com/1286410/98365412-adb97c00-2032-11eb-8ff6-29c6bd47b27d.jpg)

**Comment by ttempleton** [comment]
@skoften is that with using the Facebook API key in the Embedded Assets settings?

Regarding the Embed update: Embedded Assets supports Embed 3, and won't support Embed 4 until the release of Craft 4; the reason for this being Embed 4's requirement of PHP 7.4 or later, which looks at this stage like it will also be Craft 4's minimum PHP requirement.  However, Embed 3.4.9 should have fixed Instagram embedding (using the Facebook API key as the access token).

**Comment by skoften** [comment]
@ttempleton without a key at the moment. Can you tell me which key we need exactly? Little bit confused here. Do I need to fill in an app secret or an access token?

**Comment by ishetnogferre** [comment]
Same for us

We've tried adding a Facebook Token using both these methods:
- Access Token: App ID | App Secret (https://developers.facebook.com/docs/facebook-login/access-tokens#apptokens)
- Client Access Token: App ID | Client token (https://developers.facebook.com/docs/instagram/oembed/#client-access-tokens)

The Client Access Token seems to work for now.
But we are still getting the information from the login screen (see screenshot)
![Screenshot 2020-11-09 at 10 34 45](https://user-images.githubusercontent.com/6649706/98524296-57894a80-2277-11eb-9c47-08b0d9678890.png)

**Comment by ttempleton** [comment]
Glad to hear the client access token is working, @ishetnogferre.  I'm going to close this now as it seems like everything is working okay on the Embedded Assets side of things.  Regarding getting the login page information, Embedded Assets can only really work with the data returned by Embed, so I'm going to recommend setting up a test of Embed 3 on the server where that's happening.  If it turns out that the Embed 3 test works fine, then feel free to open a new issue here, but otherwise I'd recommend opening an issue with them.

**Comment by skoften** [comment]
Did some extra testing because it was still not working. Think I solved it; to have to add "oEmbed" to the products of the Facebook app. 

![Screenshot 2020-11-09 at 12 04 35](https://user-images.githubusercontent.com/1286410/98533932-fa47c600-2283-11eb-9668-d797b8e0fcf1.jpg)

Also, be sure to combine the app key with the client key;

![Screenshot 2020-11-09 at 12 04 50](https://user-images.githubusercontent.com/1286410/98533966-0895e200-2284-11eb-94a2-364b4d06ff1d.jpg)

After this we got it working.

**Comment by sjcallender** [comment]
@skoften - I'm doing everything you've done and I still can't get all the data. I think it's because you have Instagram Graph API approved in your Facebook Developers app. They keep rejecting my submissions. Any insights into that process?

![image](https://user-images.githubusercontent.com/984311/100110505-02cefd80-2e3b-11eb-9e55-c32d949f6370.png)
