### ISSUE TITLE
Use Craft's cache service layer instead of manually writing files to storage/runtime/assets?

### ISSUE THREAD

**Issue by johndwells** [spicywebau/craft-embedded-assets#158]
I'm using Embedded Assets on a site being built on Servd (https://servd.host), and one of the wonderful features of Servd is that a code deployment involves a complete rebuild of the web application. This means that any filesystem content (such as the contents of `storage`) is ephemeral and nuked on deployment.

As a result, I have noticed that after a rebuild the front-end takes a very long time to re-render a page that holds a lot of Embedded Assets thumbnails. After doing some digging I discovered that it's because Embedded Assets is _manually writing_ a cached copy of the JSON contents into `storage/assets/embeddedassets/`:

https://github.com/spicywebau/craft-embedded-assets/blob/master/src/Service.php#L628:

```
FileHelper::writeToFile($cachedPath, $contents);
```

I understand why the contents of the JSON file are cached (to account for assets stored in remote volumes), but I wonder if it should/could use Craft's cache service layer instead of manually writing to `/storage`?

That way, in the case of Servd which uses Redis as the cache, data would persist across builds.

I am open to submitting a PR if you are open to this change. I'm also open to considering other solutions if there were reasons behind not using the cache layer in the first place...

Thanks!

**Comment by johndwells** [comment]
Any thoughts on this, and/or the PR? If the PR isn't an appropriate solution I would love to consider an alternative that doesn't rely on writing manually to the filesystem... Thanks!

**Comment by ttempleton** [comment]
Thanks for the PR, @johndwells.  You're right that using the Craft cache would be better if file storage causes issues in cases like this.  That said, given that Craft installs that already take advantage of the file storage to speed up their embedded asset loads would have to regenerate the cached versions -- giving them one more long page load after the update to the new system if the file storage system is immediately abandoned -- I'd like to retain the file storage (for loading and deleting the files, at least), rather than removing it entirely at this point.  I'm imagining something like:

- If Embedded Assets can't find the embedded asset data it's looking for in the Craft cache, look for the file in `/storage`
- If it finds that file, insert its contents into the Craft cache and delete it

Which looks like it would be a small addition to the changes you've made to `_getAssetContents()`.  I welcome any thoughts you have on that, and if that sounds good then I'd be happy to merge the PR, implement the local-file-reading fallback and release the new version.

**Comment by johndwells** [comment]
@ttempleton Thanks for your input! I appreciate the concern about the existing installs, your suggestion seems quite sensible.

Great plugin btw, it's our absolute go-to for handling videos with our clients. Thanks again for welcoming the PR, looking forward to the release!

**Comment by ttempleton** [comment]
Embedded Assets 2.5.0 has now been released, thanks again!

**Comment by johndwells** [comment]
@ttempleton Thanks again for facilitating this change - I can confirm that it's working perfectly as intended on the Servd.host platform. 🎊
