### ISSUE TITLE
Embed youtube-nocookie.com Domain - GDPR

### ISSUE THREAD

**Issue by thomasbendl** [spicywebau/craft-embedded-assets#173]
#### Description
I want to use GDPR conform Youtube Videos(https://www.youtube-nocookie.com) in a project. Is this possible?

Example Output!
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/FsjHqvpTRag" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

#### Other information
- Embedded Assets version: 2.8.6
- Craft CMS version: 3.6.12

**Comment by ttempleton** [comment]
It doesn't look like it's currently possible, as there doesn't seem to be a way to get YouTube to return the nocookie domain.  We'll have a look at adding a setting for it, though.

**Comment by ttempleton** [comment]
Just added a `Use Youtube nocookie domain?` setting for Embedded Assets 2.6, which will be released later this month.  It's important to note that it won't affect what gets saved in the embedded asset JSON files (i.e. the saved iframes will still use `youtube.com`) but the setting being enabled will give you embedded asset models in which the iframes use `youtube-nocookie.com` instead.  This means any existing YouTube embedded assets won't need to be replaced in order to use `youtube-nocookie.com`, but also means any YouTube embedded assets saved while the setting is enabled will revert to using `youtube.com` if the setting is disabled later.

**Comment by lukasIO** [comment]
This is great! exactly what I was looking for just now :)
