### ISSUE TITLE
Changing asset title reverts it back to it's URL

### ISSUE THREAD

**Issue by gijsstegehuis** [spicywebau/craft-embedded-assets#175]
#### Description
Doesn't happen with regular assets, so i assume it has to with this plugin.

#### Other information
- Embedded Assets version: 2.5.3
- Craft CMS version: Craft Pro 3.6.13

**Comment by gijsstegehuis** [comment]
Anyone?

**Comment by ttempleton** [comment]
Unable to reproduce this given the information provided, but that behaviour would not be caused by this plugin -- the only way Embedded Assets will get involved when an embedded asset is saved is to store a cached copy of the embedded asset data, it definitely doesn't try to replace the asset title with the URL or anything else.
