### ISSUE TITLE
Feed Me MIME error on importing youtube videos

### ISSUE THREAD

**Issue by cookie10codes** [spicywebau/craft-embedded-assets#184]
#### Description
I'm trying to move over content from our legacy to our new Craft site. I have some difficulties converting the youtube video's over to the Embedded Assets. I did it before (around the end of previous year and beginning of this year) and it worked fine. 

Now I'm getting this error on each Youtube `News: embed - Asset error: https://youtu.be/ohJ_lMl1f4s - No file extensions are known for the MIME Type text/html; charset=utf-8.`. If I copy over the youtube link and enter it through the embed url, it works fine.

#### Other information
- Embedded Assets version: 2.7.0
- Feed Me version: 4.3.6
- Craft CMS version: 3.6.17 / 3.7.0-beta.5 --> tested on both versions

**Comment by ttempleton** [comment]
It looks like the error is coming from [`craft\helpers\FileHelper::getExtensionByMimeType()`](https://github.com/craftcms/cms/blob/3.6.17/src/helpers/FileHelper.php#L723-L725).  There isn't anything in Embedded Assets that uses `getExtensionByMimeType()`, but it is used in Feed Me, in [`craft\feedme\helpers\AssetHelper::getRemoteUrlExtension()`](https://github.com/craftcms/feed-me/blob/4.3.6/src/helpers/AssetHelper.php#L350).  My testing with calling `getRemoteUrlExtension()` with your YouTube URL as the argument gives me that error, so that's likely where the error is occurring in your case and you should open an issue with Feed Me about this.

**Comment by michtio** [comment]
Thank you for the answer and test @ttempleton

**Comment by cookie10codes** [comment]
thanks @ttempleton for replying so quickly. I'll check with P&T for this issue
