### ISSUE TITLE
Prevent "blacklisted" providers to be uploaded

### ISSUE THREAD

**Issue by lassemt** [spicywebau/craft-embedded-assets#195]
#### Description
This is more of a feature request.

Let's say you whitelisted only Vimeo and Twitter, then you should be able to prevent Youtube embedding data to be uploaded. Today one has to check for this in the templating state using the `getIsSafe()` method to prevent outputting the embed. But since uploading it worked the user expect the data to work in the front-end. 

Alternatively, a solution could be setting it on the asset field level:
<img width="369" alt="Screenshot 2022-02-10 at 14 37 02" src="https://user-images.githubusercontent.com/2833312/153419092-766d26be-36c3-46f4-be9a-2073d7764fe2.png">

**Comment by ttempleton** [comment]
I think having a plugin setting to prevent embedded asset uploads from non-whitelisted providers (that defaults to the current behaviour) is a great idea. Pull requests for this are welcome, otherwise I'll put it on my todo list to add in the future.

Having this as a setting on a per-field basis would be great, and probably the preferred option if it was possible, but since Embedded Assets just uses Craft asset fields, we don't have the ability from the plugin's side to insert our own settings into the existing field settings.

**Comment by ttempleton** [comment]
The `preventNonWhitelistedUploads` plugin setting has now been added in version 3.1.0.
