### ISSUE TITLE
Instagram page not foound

### ISSUE THREAD

**Issue by wmdhosting** [spicywebau/craft-embedded-assets#209]
#### Description
Instagram preview working when dev test localy on computer.. 
But on server it does not.. 
![Snag_834b2bf](https://user-images.githubusercontent.com/76176291/169637187-c53209f7-c141-4d89-a32f-2084553d3864.png)

We tryed to turn off firewall, ngnix. 
but still same..  any idea what can be..

#### Other information
- Embedded Assets version:
- 2.10.7
- Craft CMS version:
Craft Pro 3.7.42

**Comment by ttempleton** [comment]
Firstly you should make sure you've added your Instagram API key to the Facebook Key field in Embedded Assets' settings - if you haven't done that, some of the comments in #150 may be helpful in setting that up.

If it still happens after adding that, or if you've already added that, then I recommend setting up an [Embed 3 test](https://github.com/oscarotero/Embed/tree/v3.x#usage) on the server where it's not working, and seeing if the Instagram link works with that, since Embedded Assets uses Embed 3 to get embed data. If that doesn't work, I recommend opening an issue with Embed, but if that does work, please let us know and we'll reopen this issue.
