### ISSUE TITLE
YouTube embeds are now being added as Link type instead of Video

### ISSUE THREAD

**Issue by jrrdnx** [spicywebau/craft-embedded-assets#243]
### Bug Description

Was notified by a client that recent asset embeds from YouTube are now showing as "Link" instead of "Video". These worked correctly as recently as August 28th, and no changes were made to Craft or any plugins (Craft v3.7.18.2 and Embedded Assets v2.8.1).

I updated to the latest version of Embedded Assets (2.11.4) and Craft v3 (3.9.3), and these continue to show File Kind as "Link" instead of "Video" so I don't think there's an issue with the plugin itself, but maybe a change elsewhere that needs to be accounted for.

### Steps to reproduce

1. Add YouTube URL to embed window
2. File Kind shows as "Link" instead of "Video"

### Embedded Assets version

2.11.4

### Craft CMS version

3.9.3

**Comment by ttempleton** [comment]
I'm unable to reproduce this. If it's still happening for you, could you please provide an example of a video URL that is showing the link type.

**Comment by ttempleton** [comment]
I manually added an iframe for that video to a page, and was met with a message that playback on other websites has been disabled by the video owner, so that explains why it's being added with the link type instead. The video owner would need to enable embedding of the video before it can be added with the video type.

**Comment by jrrdnx** [comment]
Thanks for your help!
