### ISSUE TITLE
Gleam Support

### ISSUE THREAD

**Issue by lazlo-bonin** [spicywebau/craft-embedded-assets#78]
Hi Benjammin! Loving Embedded Assets so far.

We run a lot of competitions on Gleam, and it would be great to be able to embed them via embedded assets. Could this be added in the future?

For reference: http://gleam.io

**Comment by ttempleton** [comment]
In general, since Embedded Assets uses [Embed 3](https://github.com/oscarotero/Embed/tree/v3.x) to get the embed data, requests to support new sites would be best posted to Embed.

Embed 3 does have the [`custom_adapters_namespace`](https://github.com/oscarotero/Embed/tree/3.4.17#the-adapter) option, which could be used to add support for new sites with your own custom Embed adapters; Embedded Assets 2.8.0 now fires an event before sending a request through Embed, which allows plugins/modules to modify the options given to Embed including `custom_adapters_namespace`.

Since Embed doesn't seem to support Gleam competition embeds at the moment ([at least the demo competition embedding attempt just returns a link](https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fgleam.io%2FiR0GQ%2Fgleam-competition-demo)) we won't add Gleam to our default URL whitelist, but if it's supported in the future, you can add it to your own Craft project's whitelist by creating the file `config/embeddedassets.php` and adding the following:

```php
<?php

return [
    'extraWhitelist' => [
        // Gleam
	'gleam.io',
    ],
];
```
