### ISSUE TITLE
YouTube playlist disparity

### ISSUE THREAD

**Issue by joshuabaker** [spicywebau/craft-embedded-assets#82]
When entering a YouTube playlist link in the control panel the correct video is shown, however, the front-end output is always the first video. Is there a difference with how these are rendered?

**Comment by laurabennett** [comment]
It seems that any parameters other than the video id are ignored.

**Comment by ttempleton** [comment]
Embedding a YouTube playlist does seem to default to the first video in the playlist, which is consistent with the embed code you'd get directly from the YouTube playlist page, but embedding a specific video from the playlist seems to correctly show that video on both the control panel and front-end. There definitely shouldn't be any difference in how the embed is rendered in the control panel and front-end unless embedded asset methods like `getIframeCode()` are being used in your templates to add parameters; admittedly I can't be sure how things were behaving back when this issue was opened, but if there were any issues with Embedded Assets / Embed / YouTube that were causing inconsistencies at that time, they appear to be resolved now.
