### ISSUE TITLE
Help requested: Support for reference tags?

### ISSUE THREAD

**Issue by readtedium** [spicywebau/craft-embedded-assets#91]
Hi there, I'm trying to figure out the best way to handle a whole bunch of embedded URLs in content that's been laid out in Markdown form with raw URLs embedded.

I'm using Doxter to manage the content, which allows me to reference assets directly in the text, but simply typing in `{asset:3502}` just gives me the raw URL for the JSON tag, which is obviously not what I'm looking for.

I can upload images as assets and get them to render in the text as  `{asset:3502:img}`. My question is, is there a similar method I could use for embedded assets? I'd specifically like to use this to handle tweets.

Just trying to get a handle on the functionality here.

**Edit:** I ended up using regex for this specific use case, but I would still be interested to hear how reference tags could be used with this plugin, if possible.

**Comment by ttempleton** [comment]
Sorry for the delay in this question being addressed. I don't think this is currently possible, unfortunately, since the embedded asset properties themselves aren't properties of the asset as required by the reference tags format. Would love to do this if it's made possible in some way in the future, though.
